name: Build Masscan

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          install: gcc make mingw-w64-ucrt-x86_64-libpcap
          update: true
      
      - name: Build
        shell: msys2 {0}
        run: |
          cd $GITHUB_WORKSPACE
          make CC=gcc
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: masscan-windows
          path: bin/masscan.exe
